name: Update Blocklist

on:
  schedule:
    - cron: "0 2 * * *"  # Runs daily at 2 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_blocklist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install requests library
        run: pip install requests

      - name: Run blocklist script
        run: python combine_blocklists.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add combined_blocklist.txt
          git commit -m "Update combined blocklist" || echo "No changes to commit"
          git push origin main
